FROM node:22-alpine AS build
WORKDIR /app
RUN npm install -g npm@11.6.1
ARG VITE_API_URL
ARG VITE_BRAND_MENDOZA_ON_LIGHT
ARG VITE_BRAND_MENDOZA_ON_BLUE
ARG VITE_BRAND_OPS_ON_LIGHT
ARG VITE_BRAND_OPS_ON_BLUE
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_BRAND_MENDOZA_ON_LIGHT=$VITE_BRAND_MENDOZA_ON_LIGHT
ENV VITE_BRAND_MENDOZA_ON_BLUE=$VITE_BRAND_MENDOZA_ON_BLUE
ENV VITE_BRAND_OPS_ON_LIGHT=$VITE_BRAND_OPS_ON_LIGHT
ENV VITE_BRAND_OPS_ON_BLUE=$VITE_BRAND_OPS_ON_BLUE
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.29-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
